apps/main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'main'

urlpatterns = [
    path('', login_required(views.HomePage.as_view()), name='index'),
    path('products/', login_required(views.ProductList.as_view()), name='products'),
    path('contractors/', login_required(views.ContractorList.as_view()), name='contractors'),
    path('documents/', login_required(views.DocumentList.as_view()), name='documents'),
    path('operations/', login_required(views.OperationList.as_view()), name='operations'),
    path('storage_items/', login_required(views.StorageItemList.as_view()), name='storage_items'),
    # path('remove_marked_objects/', login_required(views.RemoveMarkedObjects.as_view()), name='remove_marked_objects'),
    path('import_products/', login_required(views.ImportProduct.as_view()), name='import_products'),
    path('motion_report/', login_required(views.MotionReport.as_view()), name='motion_report'),
    path('products_to_xls/', login_required(views.products_to_xls), name='products_to_xls'),
    path('contractors_to_xls/', login_required(views.contractors_to_xls), name='contractors_to_xls'),
]

apps/restapi/urls.py
from django.urls import path
from rest_framework import routers
from . import views


app_name = 'api'


urlpatterns = [
    path('contractor_categories/', views.contractor_categories, name='contractor_categories'),
    path('apply_document/<int:document_id>/', views.apply_document, name='apply_document'),
    path('unapply_document/<int:document_id>/', views.unapply_document, name='unapply_document'),
    path('remove_marked_objects/', views.remove_marked_objects, name='remove_marked_objects'),
    path('import_products/', views.import_products, name='import_products'),
    path('consolidated_report/', views.consolidated_report, name='consolidated_report'),
    path('motion_report/', views.motion_report, name='motion_report'),
]


router = routers.SimpleRouter()
router.register('products', views.ProductViewSet, basename='products')
router.register('contractors', views.ContractorViewSet, basename='contractors')
router.register('operations', views.OperationViesSet, basename='operations')
router.register('documents', views.DocumentViewSet, basename='documents')
router.register('document_items', views.DocumentItemViewSet, basename='document_items')
router.register('storage_items', views.StorageItemViewSet, basename='storage_items')
urlpatterns.extend(router.urls)

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('api/', include('apps.restapi.urls')),
    path('', include('apps.main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

templates/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'menu.css' %}">
    <link rel="stylesheet" href="{% static 'buttons.css' %}">
    <link rel="stylesheet" href="{% static 'modals.css' %}">
    <link rel="stylesheet" href="{% static 'inputs.css' %}">
    <link rel="stylesheet" href="{% static 'content.css' %}">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <link rel="stylesheet" href="{% static 'search_elements.css' %}">
    <script src="{% static 'jquery-3.5.1.js' %}"></script>
    <script src="{% static 'common.js' %}"></script>
    <title>AnnSkachkova</title>
</head>
<body>

{% block message %}
{% endblock %}

{% block menu %}
{% endblock %}

{% block content %}
{% endblock %}

{% block modals %}
{% endblock %}

{% block scripts %}
{% endblock %}
</body>
</html>

templates/consolidated_report.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <div class="basic-div content-div"><strong>Сводный отчет по базе данных</strong></div>
    <div class="basic-div content-div" id="content-div">
        <p>Отправляю запрос на формирование отчета...</p>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const apiConsolidatedReportURL = "/api/consolidated_report/";
        let reportsDescriptions = [
            {
                key: "product_count",
                description: "Общее количество наименований товаров в справочнике"
            },
            {
                key: "contractor_count",
                description: "Общее количество наименований контрагентов в справочнике"
            },
            {
                key: "storage_item_count",
                description: "Общее количество наименований товаров на складе"
            },
            {
                key: 'total_cost',
                description: "Общая стоимость товаров на складе"
            }
        ]

        let $contentDiv = $("#content-div");

        $.ajax(apiConsolidatedReportURL, {
            "method": "GET",
            "dataType": "json",
            "success": function (data) {
                $contentDiv.empty();

                for (let {key, description} of reportsDescriptions) {
                    $contentDiv.append(
                        $("<p>")
                            .addClass("report-block")
                            .append($("<strong>").text(description + ": "))
                            .append($("<span>").text(data[key]))
                    );
                }
            },
            "error": function (jqXHR) {
                $contentDiv.empty();
                showAjaxError(jqXHR);
            }
        });
    </script>
{% endblock %}

templates/contractors.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <div class="basic-div content-div"><strong>Справочник контрагентов</strong></div>
    <div class="basic-div content-div" id="content-div">
        <div class="operation-div">
            <span class="span-button" id="create-button">Создать</span>
            <input type="text" name="search-field" id="search-field" value="">
            <span class="span-button" id="search-button">Найти</span>
            <span class="span-button" id="clear-search-field-button">Очистить</span>
        </div>
        <table id="content-table" class="content-table">
            <tr>
                <th column-key="id" display-name="Номер">Номер</th>
                <th column-key="title" display-name="Наименование">Наименование</th>
                <th column-key="category" display-name="Категория">Категория</th>
                <th column-key="dt_created" display-name="Дата создания">Дата создания</th>
                <th column-key="dt_updated" display-name="Дата изменения">Дата изменения</th>
                <th column-key="to_remove" display-name="Удл.">Удл.</th>
            </tr>
        </table>
        <div class="navigation-div">
            <span class="span-button" id="prev-page-button">Предыдущая страница</span>
            <span class="span-button" id="next-page-button">Следующая страница</span>
        </div>
    </div>
{% endblock %}

{% block modals %}
    <div class="modal" id="contractor-editor" style="display: none">
        <div>
            <div class="modal-control-buttons">
                <span class="span-button" id="contractor-editor-close-button">X</span>
            </div>
            <div>
                Номер: <span id="contractor-number"></span><br><br>
                Дата создания: <span id="contractor-dt-created"></span><br><br>
                Дата изменения: <span id="contractor-dt-updated"></span><br><br>
                <fieldset>
                    Наименование:<br><input type="text" name="contractor-title" id="contractor-title" value="" required><br><br>
                    Категория:
                    <select name="contractor-category" id="contractor-category"></select><br><br>
                    Пометить на удаление: <input type="checkbox" name="contractor-to-remove" id="contractor-to-remove">
                </fieldset>
            </div>
            <br>
            <div class="modal-control-buttons">
                <span class="span-button" id="contractor-editor-cancel-button">Отмена</span>
                <span class="span-button" id="contractor-editor-save-button">Сохранить</span>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const apiURL = "/api/contractors/";

        const apiContractorCategoriesURL = "/api/contractor_categories/";
        let contractorCategories = null;

        function checkContractorFormData() {
            if ($("#contractor-title").val().trim() === "") {
                throw new Error("Наименование не может быть пустым!")
            }
        }

        function showContractors(url) {
            if (!contractorCategories) {
                $.ajax(apiContractorCategoriesURL, {
                    "method": "GET",
                    "dataType": "json",
                    "async": false,
                    "success": function (data) {
                        contractorCategories = data;
                    }
                })
            }
            $.ajax(url, {
                "method": "GET",
                "dataType": "json",
                "success": function (data) {
                    let contractors, nextPage, prevPage;
                    if ("results" in data) {
                        contractors = data.results;
                        nextPage = data.next;
                        prevPage = data.previous;
                    } else {
                        contractors = [data];
                        nextPage = prevPage = null;
                    }

                    //Создаем таблицу со списком контрагентов
                    let $contentTable = $("#content-table");
                    $("tr:not(:first-child)", $contentTable).remove()
                    let $tableRow = null;
                    for (let contractor of contractors) {
                        formatDates(contractor);
                        $tableRow = $("<tr>");
                        $tableRow.append($("<td>").text(contractor.id));
                        $tableRow.append($("<td>").text(contractor.title));
                        $tableRow.append($("<td>").text(contractorCategories[contractor.category]));
                        $tableRow.append($("<td>").text(contractor.dt_created));
                        $tableRow.append($("<td>").text(contractor.dt_updated));
                        $tableRow.append($("<td>").text(contractor.to_remove ? "X" : "-"));
                        $tableRow.data("contractor", contractor);
                        $contentTable.append($tableRow);
                    }
                    $contentTable.on("click", "tr:not(:first-child)", contractorEdit);

                    createPaginationButtons(prevPage, nextPage, showContractors);
                },
                "error": function (jqXHR) {
                    showAjaxError(jqXHR, $("#contractor-editor"));
                }
            })
        }

        function contractorEdit() {
            let selectedContractor = $.data(this, "contractor");

            let $row = $(this);

            showModal($("#contractor-editor"));
            $("#contractor-number").text(selectedContractor.id);
            $("#contractor-dt-created").text(selectedContractor.dt_created);
            $("#contractor-dt-updated").text(selectedContractor.dt_updated);
            $("#contractor-title").val(selectedContractor.title);
            let categoriesList = [];
            for (let [key, value] of Object.entries(contractorCategories)) {
                categoriesList.push($("<option>").val(key).text(value));
                if (key === selectedContractor.category) {
                    categoriesList[categoriesList.length - 1].prop("selected", true);
                }
            }
            $("#contractor-category").empty().append(...categoriesList);
            $("#contractor-to-remove").prop("disabled", false);
            $("#contractor-to-remove").prop("checked", selectedContractor.to_remove);

            $("#contractor-editor-save-button").off().click(() => {
                //Проверяем корректность внесения данных в форму
                try {
                    checkContractorFormData();
                } catch (error) {
                    alert(error.message);
                    return;
                }

                let urlForRequest = `${apiURL}${selectedContractor.id}/`;
                $.ajax(urlForRequest, {
                    "method": "PATCH",
                    "dataType": "json",
                    "data": {
                        "title": $("#contractor-title").val(),
                        "category": $("#contractor-category").val(),
                        "to_remove": $("#contractor-to-remove:checked").val() ? true : false
                    },
                    "success": function (data) {
                        formatDates(data);

                        $row.empty();
                        $row.append($("<td>").text(data.id));
                        $row.append($("<td>").text(data.title));
                        $row.append($("<td>").text(contractorCategories[data.category]));
                        $row.append($("<td>").text(data.dt_created));
                        $row.append($("<td>").text(data.dt_updated));
                        $row.append($("<td>").text(data.to_remove ? "X" : "-"));
                        $row.data("contractor", data);

                        closeModal($("#contractor-editor"));
                    },
                    "error": function (jqXHR) {
                        showAjaxError(jqXHR, $("#contractor-editor"));
                    }
                })
            })
        }

        function contractorCreate() {
            showModal($("#contractor-editor"));

            $("#contractor-number").text("-");
            $("#contractor-dt-created").text("-");
            $("#contractor-dt-updated").text("-");
            $("#contractor-title").val("");
            let categoriesList = [];
            for (let [key, value] of Object.entries(contractorCategories)) {
                categoriesList.push($("<option>").val(key).text(value));
            }
            categoriesList[0].prop("selected", true);
            $("#contractor-category").empty().append(...categoriesList);
            $("#contractor-to-remove").prop("disabled", true);
            $("#contractor-to-remove").prop("checked", false);

            $("#contractor-editor-save-button").off().click(() => {
                try {
                    checkContractorFormData();
                } catch (error) {
                    alert(error.message);
                    return
                }

                $.ajax(apiURL, {
                    "method": "POST",
                    "dataType": "json",
                    "data": {
                        "title": $("#contractor-title").val(),
                        "category": $("#contractor-category").val()
                    },
                    "success": function (data) {
                        closeModal($("#contractor-editor"));
                        $("#search-field").val(data.id);
                        showContractors(`${apiURL}${data.id}`);
                    },
                    "error": function (jqXHR) {
                        showAjaxError(jqXHR, $("#contractor-editor"));
                    }
                })
            })
        }

        let contractorSearch = getSearchFunction(showContractors, getDefaultSearchParams, apiURL);

        let contractorSort = getSortFunction(showContractors, getDefaultSearchParams, apiURL);

        $("#clear-search-field-button").click(() => {
            $("#search-field").val("");
            contractorSearch();
        });
        $("#create-button").click(contractorCreate);
        $("#search-button").click(contractorSearch);
        $("#contractor-editor-close-button, #contractor-editor-cancel-button").click(() => closeModal($("#contractor-editor")));
        $("#content-table th").click(contractorSort);

        showContractors(apiURL);
    </script>
{% endblock %}

templates/import_products.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <div class="basic-div content-div"><strong>Импорт справочника товаров</strong></div>
    <div class="basic-div content-div" id="content-div">
        <table class="content-table">
            <tr>
                <th>Наименование</th>
                <th>Цена</th>
            </tr>
            <tr>
                <td>Товар 1</td>
                <td>1000</td>
            </tr>
            <tr>
                <td>Товар 2</td>
                <td>2000</td>
            </tr>
            <tr>
                <td>Товар 3</td>
                <td>1500</td>
            </tr>
        </table>
        <br>
        <div class="operation-div">
            Выберите файл: <input type="file" name="file" id="file" accept=".xlsx">
            <span class="span-button" id="import-button">Импортировать</span>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const apiImportProductsURL = "/api/import_products/";

        $("#import-button").click(() => {
            let file = $("#file").prop("files")[0];

            let formData = new FormData();
            formData.append("uploaded_file", file);

            $.ajax(apiImportProductsURL, {
                "method": "POST",
                "data": formData,
                "processData": false,
                "contentType": false,
                "success": function () {
                    showMessage("Файл успешно импортирован");
                },
                "error": function (jqXHR) {
                    showAjaxError(jqXHR);
                }
            })
        });
    </script>
{% endblock %}

templates/index.html
{% extends 'base_template.html' %}

{% block message %}
    <div class="modal" id="message-block" style="display: none">
        <div>
            <div class="modal-control-buttons">
                <span class="span-button" id="message-block-close-button">X</span>
            </div>
            <div>
                <p></p>
            </div>
            <div class="modal-control-buttons">
                <span class="span-button" id="message-block-ok-button">Ок</span>
            </div>
        </div>
    </div>

    <script>
        $("#message-block-close-button, #message-block-ok-button").click(() => {
            closeModal($("#message-block"))
        });
    </script>
{% endblock %}

{% block menu %}
    <div id="header">
        <div class="basic-div">
            <ul id="menu">
                <li>
                <span>
                    {% if user.first_name or user.last_name %}
                        {{ user.get_full_name }}
                    {% else %}
                        {{ user }}
                    {% endif %}
                </span>
                    <ul>
                        <li>
                        <span>
                            <a href="{% url 'logout' %}">Выйти</a>
                        </span>
                        </li>
                    </ul>
                </li>
                <li>
                    <span>Справочники</span>
                    <ul>
                        <li>
                            <span>
                                <a href="{% url 'main:products' %}">Товары</a>
                            </span>
                        </li>
                        <li>
                            <span>
                                <a href="{% url 'main:contractors' %}">Контрагенты</a>
                            </span>
                        </li>
                    </ul>
                </li>
                <li>
                    <span>
                        <a href="{% url 'main:documents' %}">Документы</a>
                    </span>
                </li>
                <li>
                    <span>Отчеты</span>
                    <ul>
                        <li>
                            <span>
                                {% comment %} <a href="{% url 'main:consolidated_report' %}">Сводный отчет по базе данных</a> {% endcomment %}
                            </span>
                        </li>
                        <li>
                            <span>
                                <a href="{% url 'main:motion_report' %}?report_type=products">Отчет по движениям товаров</a>
                            </span>
                        </li>
                        <li>
                            <span>
                                <a href="{% url 'main:motion_report' %}?report_type=contractors">Отчет по операциям с контрагентами</a>
                            </span>
                        </li>
                        <li>
                            <span>
                                <a href="{% url 'main:products_to_xls' %}">Список товаров (XLS)</a>
                            </span>
                        </li>
                        <li>
                            <span>
                                <a href="{% url 'main:contractors_to_xls' %}">Список контрагентов (XLS)</a>
                            </span>
                        </li>
                    </ul>
                </li>
                <li>
                    <span>Сервис</span>
                    <ul>
                        {% if user.is_superuser %}
                            <li>
                                <span>
                                    <a href="/admin/">Администрирование</a>
                                </span>
                            </li>
                            <li>
                                <span>
                                    <a href="{% url 'main:remove_marked_objects' %}">Удаление помеченных объектов</a>
                                </span>
                            </li>
                            <li>
                                <span>
                                    <a href="{% url 'main:import_products' %}">Импорт товаров</a>
                                </span>
                            </li>
                            <li>
                                <span>
                                    <a href="{% url 'main:storage_items' %}">Управление остатками</a>
                                </span>
                            </li>
                        {% else %}
                            <li>
                                <span>
                                    <a href="{% url 'main:storage_items' %}">Просмотр остатков</a>
                                </span>
                            </li>
                        {% endif %}
                        <li>
                            <span>
                                <a href="{% url 'main:operations' %}">Журнал операций</a>
                            </span>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base_template.html' %}

{% block content %}
    <div class="basic-div login-div">
        {% if user.is_authenticated %}
            Вы уже выполнили вход на сайт
            <a href="{% url 'main:index' %}">Перейти на главную страницу</a>
        {% else %}
            <form method="post">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>
                            Имя пользователя
                        </td>
                        <td>
                            {{ form.username }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Пароль:
                        </td>
                        <td>
                            {{ form.password }}
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Войти"></td>
                    </tr>
                </table>
                <input type="hidden" name="next" value="{{ next }}">
                <input type="hidden" id="user-token" name="user_token" value="">
            </form>
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="loginErrorField">{{ error }}</p>
                {% endfor %}
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    <script>
        let tokenField = document.getElementById("user-token");
        let symbols = "0123456789qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM";
        let token = []
        for (let i = 0; i < 32; i++) token.push(symbols[Math.floor(Math.random() * symbols.length)]);
        token = token.join("");
        tokenField.value = token;
        localStorage.setItem("user_token", token)
    </script>
{% endblock %}

templates/operations.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <div class="basic-div content-div"><strong>Журнал операций</strong></div>
    <div class="basic-div content-div" id="content-div">
        <div class="operation-div">
            <input type="text" name="search-field" id="search-field" value="">
            <span class="span-button" id="search-button">Найти</span>
            <span class="span-button" id="clear-search-field-button">Очистить</span>
        </div>
        <table id="content-table" class="content-table">
            <tr>
                <th>Дата</th>
                <th>Пользователь</th>
                <th>Операция</th>
            </tr>
        </table>
        <div class="navigation-div">
            <span class="span-button" id="prev-page-button">Предыдущая страница</span>
            <span class="span-button" id="next-page-button">Следующая страница</span>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const apiURL = "/api/operations/";

        function showOperations(url) {
            $.ajax(url, {
                "method": "GET",
                "dataType": "json",
                "success": function (data) {
                    let operations = data.results;
                    let nextPage = data.next;
                    let prevPage = data.previous;

                    //Создаем таблицу со списком контрагентов
                    let $contentTable = $("#content-table");
                    $("tr:not(:first-child)", $contentTable).remove()
                    let $tableRow = null;
                    for (let operation of operations) {
                        formatDates(operation);
                        $tableRow = $("<tr>");
                        $tableRow.append($("<td>").text(operation.dt_created));
                        $tableRow.append($("<td>").text(operation.username));
                        $tableRow.append($("<td>").text(operation.operation));
                        $contentTable.append($tableRow);
                    }

                    createPaginationButtons(prevPage, nextPage, showOperations);
                },
                "error": function (jqXHR) {
                    showAjaxError(jqXHR, $("#contractor-editor"));
                }
            })
        }

        let operationSearch = getSearchFunction(showOperations, getDefaultSearchParams, apiURL);

        $("#clear-search-field-button").click(() => {
            $("#search-field").val("");
            operationSearch();
        });
        $("#search-button").click(operationSearch);

        showOperations(apiURL);
    </script>
{% endblock %}

templates/remove_marked_objects.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <div class="basic-div content-div"><strong>Удаление помеченных объектов</strong></div>
    <div class="basic-div content-div" id="content-div">
        <p>Отправляю запрос на удаление помеченных объектов...</p>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const apiRemoveObjectsURL = "/api/remove_marked_objects/";

        let $contentDiv = $("#content-div");

        $.ajax(apiRemoveObjectsURL, {
            "method": "POST",
            "dataType": "json",
            "success": function (data) {
                $contentDiv.empty();

                let successList, failList, $successList, $failList, $reportBlock;
                for (let deleteDescription of data) {
                    successList = deleteDescription['success_list'];
                    failList = deleteDescription['fail_list'];

                    $reportBlock = $("<p>").addClass("report-block");
                    $reportBlock.append($("<strong>").text(deleteDescription.description));

                    if (successList.length !== 0) {
                        $reportBlock.append($("<p>").text("Успешно удалены:"));
                        $successList = $("<ul>");
                        for (let successObj of successList) {
                            $successList.append($("<li>").text(successObj));
                        }
                        $reportBlock.append($successList);
                    }

                    if (failList.length !== 0) {
                        $reportBlock.append($("<p>").text("Не удалось удалить:"));
                        $failList = $("<ul>");
                        for (let failObj of failList) {
                            $failList.append($("<li>").text(failObj));
                        }
                        $reportBlock.append($failList);
                    }

                    $contentDiv.append($reportBlock);
                }
            },
            "error": function (jqXHR) {
                $contentDiv.empty();
                showAjaxError(jqXHR);
            }
        })

        //TODO Вставить скрипты отправки запроса на удаление
    </script>
{% endblock %}